# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [244]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [245]:
A = np.arange(1, 16).reshape(3,5)

In [246]:
#dimension
print('Dimension:', A.ndim)

#shape
print('Shape:', A.shape)

#size
print('Size:', A.size)

#datatype
print('Datatype:',A.dtype)

Dimension: 2
Shape: (3, 5)
Size: 15
Datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [250]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print('B:\n',B)
print()
print('C:\n',C)

B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

C:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [251]:
#Elementwise subtraction
print('B-C:\n', B - C, '\n')

#Elementwise multiplication
print('B*C:\n', B * C, '\n')

#Matrix multiplication
print('B@C:\n', B @ C) #alternative as expected with @ operator

B-C:
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]] 

B*C:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]] 

B@C:
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [157]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [232]:
#Exponentiate each number elementwise
print('Exp:\n', np.exp(B), '\n')

#Calculate the minimum value in the whole matrix
print('Min:', np.min(B), '\n')

#Calculcate the minimum value in each row
print('Min(row):', np.min(B,axis = 1), '\n')

#Calculcate the minimum value in each column
print('Min(column):', np.min(B,axis = 0), '\n') 

#Find the index value for the minimum value in the whole matrix
print('Index min:', np.argmin(B), '\n')

#Find the index value for the minimum value in each row
print('Index min(row):', np.argmin(B,axis = 1), '\n')

#Calculate the sum for all elements
print('Sum:', np.sum(B), '\n')

#Calculate the mean for each column
print('Mean(column):', np.mean(B,axis = 0), '\n')

#Calculate the median for each column
print('Median(column):', np.median(B,axis = 0))

Exp:
 [[ 7.3890561   2.71828183]
 [ 2.71828183 20.08553692]] 

Min: 1 

Min(row): [1 1] 

Min(column): [1 1] 

Index min: 1 

Index min(row): [1 0] 

Sum: 7 

Mean(column): [1.5 2. ] 

Median(column): [1.5 2. ]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [159]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [160]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

When fewer indices are provided than the number of axes, the missing indices are considered complete slices which means that all elements along that axis will be selected.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [161]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [162]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [163]:
for x in A.flat: #First I prefered .flat attribute to iterate through the array elementwise.
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [164]:
for x in np.nditer(A):  #Another way to do it.Here I used the np.nditer function to iterate through the array elementwise.
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

The code is starting with a matrice that include numbers up to 30(30 is not include). And then returns the array with a modified shape which returns two matrices with 3 rows and columns are created as needed for numbers.

In [252]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [259]:
#creating two matrices named m1 and m2
m1 = np.array([[1, 2],
               [3, 4]]) 

m2 = np.array([1, 1])

print('m1+m2:\n', m1 + m2) #addition of m1 and m2
print('m1 shape:', m1.shape)#To check the shape of matrice if both are same size or not, used the shape attribute. 
print('m2 shape:', m2.shape) #And the same checking for m2. 

m1+m2:
 [[2 3]
 [4 5]]
m1 shape: (2, 2)
m2 shape: (2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [167]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [262]:
A = np.arange(1, 5).reshape(2,2) #one matrice with number up to 5 and has 2 rows, 2 columns(2,2).
print(A,'\n')

b = np.array([2, 2]) #one matrice with 1 row 2 columns(2,1).
print(b, '\n')

print(b.shape, '\n') #checking the shape of b which is (2,1).

print(A + b)  #addition of A and b works, even the first matrice column and the second matrice row have not same shape.

[[1 2]
 [3 4]] 

[2 2] 

(2,) 

[[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.8, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.15, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [263]:
A = np.array([[2, 1, -1],
              [1, -1, 1]])

B = np.array([[4, -2, 1],
              [2, -4, -2]])

C = np.array([[1, 2],
              [2, 1]])

D = np.array([[3, 4],
              [4, 3]])

E = np.array([[1],
              [2]])

print("A:\n",A, '\n')

print("B:\n",B, '\n')

print("C:\n",C, '\n')

print("D:\n",D, '\n')

print("E:\n",E)

A:
 [[ 2  1 -1]
 [ 1 -1  1]] 

B:
 [[ 4 -2  1]
 [ 2 -4 -2]] 

C:
 [[1 2]
 [2 1]] 

D:
 [[3 4]
 [4 3]] 

E:
 [[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [265]:
def add_mult_matrices(matrix1, matrix2, operation):
    
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError("Both matrices must be of type numpy.ndarray")
        
    if operation not in ["add", "multiply"]:
        raise ValueError("The third argument must be either 'add' or 'multiply'")
        
    if operation == "add":
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same shape for addition")
        return matrix1 + matrix2
    
    else:
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix for multiplication")
        return np.matmul(matrix1, matrix2)


In [266]:
#B − 2A
add_mult_matrices(B, -2*A, 'add') 

ValueError: Matrices must have the same shape for addition

In [267]:
#3C - E
add_mult_matrices(3*C, - E, 'add')

ValueError: Matrices must have the same shape for addition

In [268]:
#A*C
add_mult_matrices(A,C, 'multiply') 
#returns error,because number of columns in the first matrix must be equal to the number of rows in the second matrix for multiplication

ValueError: Number of columns in the first matrix must be equal to the number of rows in the second matrix for multiplication

In [269]:
# C*D
add_mult_matrices(C,D, 'multiply')

ValueError: Number of columns in the first matrix must be equal to the number of rows in the second matrix for multiplication

In [270]:
# C*B
add_mult_matrices(C,B, 'multiply')

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

**Chap2. Question 2**

In [271]:
A = np.array([[1, 2], 
              [2, 4]])

B = np.array([[2, 1], 
              [1, 3]])

C = np.array([[4, 3], 
              [0, 2]])

AB = add_mult_matrices(A, B, 'multiply')
AC = add_mult_matrices(A, C, 'multiply')

print("AB:\n", AB, '\n\n', "AC:\n", AC) 

AB:
 [[ 4  7]
 [ 8 14]] 

 AC:
 [[ 4  7]
 [ 8 14]]


In [272]:
#To verify that AB = AC and B ̸= C

#AB = AC
print((AB == AC).all()) # AB and AC multiplications have same results so output should be True.

#B != C 
print((B != C).all())  # B and C are not equal as it was in question so output should be True.

True
True


**Chap2. Question 3**

In [273]:
A = np.array([[1, 1, 1], 
              [1, 2, 3], 
              [1, 3, 4]]) 

D = np.array([[2, 0, 0], 
              [0, 3, 0], 
              [0, 0, 4]]) 

#print out multipication of D and A matrices.
print('AD:\n', add_mult_matrices(A,D, 'multiply'),'\n\n', 'DA:\n', add_mult_matrices(D,A, 'multiply'))

AD:
 [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]] 

 DA:
 [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.8, Question 2**

In [274]:
A = np.array([[1, -1],
              [-1, 1]]) 

B = np.array([[-1, 1],
              [1, -1]])

print('AB:\n', add_mult_matrices(A,B,'multiply')) ##print out multipication of A and B matrices.

AB:
 [[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [315]:
A1 = np.array([[5, 6],
              [4, 5]])

A2 = np.array([[6, 4],
              [3, 3]])

In [316]:
A1_inv = np.linalg.inv(A1)

print('Inverse of A1:\n', A1_inv)

print(A1 @ A1_inv)
print(np.allclose(A1 @ A1_inv, np.eye(2)))

Inverse of A1:
 [[ 5. -6.]
 [-4.  5.]]
[[ 1.00000000e+00  0.00000000e+00]
 [-1.77635684e-15  1.00000000e+00]]
True


In [317]:
#Using np.linalg.inv() function to find the inverses of the matrices b.
A2_inv = np.linalg.inv(A2)

print('Inverse of A2:\n', A2_inv)

print(A2 @ A2_inv)
print(np.allclose(A2 @ A2_inv, np.eye(2)))

Inverse of A2:
 [[ 0.5        -0.66666667]
 [-0.5         1.        ]]
[[1. 0.]
 [0. 1.]]
True


**Quiz p.15, Question 3**

In [332]:
A = np.array([[2, 2], 
              [1, 2]])

A_inv = np.linalg.inv(A)
print('Inverse of A:\n', A_inv, '\n')
print('A @ A_inv :\n', A @ A_inv, '\n')
print(np.allclose(A @ A_inv, np.eye(2)))

Inverse of A:
 [[ 1.  -1. ]
 [-0.5  1. ]] 

A @ A_inv : 
 [[1. 0.]
 [0. 1.]] 

True


**Chap10. Question 1 a)**

In [334]:
A1 = np.array([[3, -7, -2], 
              [-3, 5, 1], 
              [6, -4, 0]])

A2 = np.array([-7, 5, 2])

B = np.linalg.solve(A1, A2) #using .solve funktion to find solution
print('B:\n', B, '\n')
print('A1 @ B :\n', A1 @ B)

B:
 [ 3.  4. -6.] 

A1 @ B :
 [-7.  5.  2.]


**Chap10. Question 1 b)**

In [335]:
A1 = np.array([[1, -2, 3], 
               [-1, 3, -1], 
               [2, -5, 5]])

A2 = np.array([1, -1, 1])

B = np.linalg.solve(A1,A2)
print('B:\n', B, '\n')
print('A1 @ B :\n', A1 @ B) 

B:
 [ 8.  2. -1.] 

A1 @ B :
 [ 1. -1.  1.]


**Chap 12. Question 1**

In [340]:
a = np.array([[3, -7, -2], 
              [-3, 5, 1], 
              [6, -4, 0]])

a_inv= np.linalg.inv(a)
print("Inverse of a:\n", a_inv)

print(a @ a_inv)
print(np.allclose(a @ a_inv, np.eye(3)))

Inverse of a:
 [[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.44089210e-16  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [341]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2) 

[0 1 2 3]
[2 3]


In [342]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [343]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In the last 3 cells I checked all the codes and texts which are correct so I assumed that there is not anything else needs to be done in these part.